script: bash ./deploy.sh
language: java
jdk:
- oraclejdk8
env:
  global:
  - GH_REF: github.com/mapsquare/h2geo.git
  - secure: ejhhr0VI2fnQ8/XerqGVoQ2VY7cxH2hXFgALfVl0/Zk3R6kdKVrkYWNqm3ILOE/B3SG0zPvFzfssb7PWX1gdhA3/S+LciXoLDQFgdtFpExpEG85HfxccU3Hdd8IO4PyKwDnY3VtgX1A9bOkjz6XRbDSP0bD8R3annRG+JHyumlBJe2FNuUlc3wojKgihUWgdOyXNh+gdXRmdbbI2lkEQb0I5kHHk+N14wuimfmvn4OfQoFVLciKr2dwYX7UQ96SU0RTXt38Ch1hbFU43oBpnbNMUdzEnLQU6g/xqMxCSEM79UvrKhjZINJ8R6CEfYpWODKcrg61JzRuO4gwGd+zCOXteosJWFnsHaBKzX4sUAzfD5mQqASxMreIAdyPD/aMjaFawC0NUVzUqV0VrGztry+zJSHsKiKMeC5ul/1blttnTDARZWsoIYJkw2X5Ks5Aj6U0JEi9Sv5JqScMUCxT1JSQkoOShcGYTRtkq5rA23R1eT5DwClDaIxT8H8ZT+OlgSPf/A/aheW4ndQz1M5ZkBm8wxeKEPt2O46RDyE+2P+YUIW0esbuWRO0+4S6LjuOAa1yOTI9IAQGXioe9K0f7fRNQC7PMAo9ZPLbGn0VlL1DoHIdMoGdzVTfSJS7Kl10ZyesjkomsiFxJyrnC+G++V4QW1BWNq0UM+PRiBWsiST0=
