script: bash ./deploy.sh
language: java
jdk:
- oraclejdk8
env:
  global:
  - GH_REF: github.com/mapsquare/h2geo.git
  - secure: V6FabfC1JEbVH4rNsYNHCKa8hUtptaFs2vJ4xIdw2irnmeZ0gTXYQbiAuOk3T9V0Yk5W6ZNoszrHX8/Te6GXvyI6W+H623jPyJ9iwEaoQ+AWnx0xRxXb1yO+PS7YJDK41VkFajNGu9k9X9SEDoyS3pnPVxrFkdv/yz+zVv8MjRwf+BYj1KJkmD1+IhQqri9LAQ8Scr83zeKGjXEIWASl5bul06CHhJPTA2IX1VphwRyMNryC8iisd6Y0/lYWeT7XIe3AFAsk34pj3mhxmf2jZJ2ImF8FKDZq8+L1CcOD4YHX61li9SfsfcZhm52TxtQXUwseM6g6+pnHwvhHhEnYPv0wUsP2SRw7AX8BJmTqPg2HKUKIowHUDlVoJQrqybgNouT6vJCEm7UOnpG0N9RApZqsEHh7xwitj/9aAdNza3VDnL8JNiBY1GxUIeh7gyglIAxL0w5ei6iVXCObCY/hrDfX/mMg3wK5OX3xzVzhoKnVP776orT1MA+Ffp0nzTQSsWGK63kDgtN00nRgz7egQ4TPgV/6NvtDWDKxiONUPTqxJFSkLTQY6u4RODx2zMeUctCj6FIeiqrfbCqn9VbWypmaBbNPRRjjj5w62gzop4cRmDac+Yts655g5NFyC7WBzpFDgsS0jMEx1JCepfMwH3zQ6dbffWnjbyeIB39JJZ0=
